name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and setup Gyp
        run: |
          git clone https://chromium.googlesource.com/external/gyp C:\build\gyp
          echo "C:\mozilla-build\python;C:\build\gyp" | Out-File -Append -Encoding ASCII -FilePath $env:GITHUB_PATH

      - name: Download and extract NSS
        run: |
          Invoke-WebRequest -Uri "https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_45_RTM/src/nss-3.45-with-nspr-4.21.tar.gz" -OutFile "C:\build\nss-3.45-with-nspr-4.21.tar.gz"
          7z x "C:\build\nss-3.45-with-nspr-4.21.tar.gz" -o"C:\build"
          7z x "C:\build\nss-3.45-with-nspr-4.21.tar" -o"C:\build"

      - name: Build NSS
        run: |
          $vswherePath = Join-Path "${env:ProgramFiles(x86)}" 'Microsoft Visual Studio\Installer\vswhere.exe'
          $vsPath = & "$vswherePath" -latest -property installationPath
          $vsDevCmd = Join-Path $vsPath 'Common7\Tools\VsDevCmd.bat'
          & cmd.exe /c "CALL `"$vsDevCmd`" -arch=amd64 && cd C:\mozilla-build\msys && msys && cd /c/build/nss-3.45/nss && ./build.sh"
        shell: powershell


