name: WSL
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Enable WSL
      run: |
        wsl --install
      shell: pwsh

    - name: Install Ubuntu on WSL
      run: |
        wsl --install
      shell: pwsh

    - name: Update and Install Dependencies on Ubuntu
      run: |
        wsl sudo apt update && sudo apt upgrade -y
        wsl sudo apt install -y build-essential git python3 ninja-build
      shell: pwsh

    - name: Install GYP on Ubuntu
      run: |
        wsl python3 -m pip install gyp-next
      shell: pwsh

    - name: Fetch NSS and NSPR
      run: |
        wsl git clone --depth=1 https://github.com/nss-dev/nss "$NSS_DIR"
        wsl hg clone https://hg.mozilla.org/projects/nspr "$NSPR_DIR"
        echo "NSS_DIR=$NSS_DIR" >> "$GITHUB_ENV"
        echo "NSPR_DIR=$NSPR_DIR" >> "$GITHUB_ENV"
        echo "NSS_JOBS=$NUMBER_OF_PROCESSORS" >> "$GITHUB_ENV"
      shell: pwsh
      env:
        NSS_DIR: /mnt/${{ github.workspace }}/nss
        NSPR_DIR: /mnt/${{ github.workspace }}/nspr

    - name: Build NSS on Ubuntu
      run: |
        wsl bash -c '
          cd "$NSS_DIR"
          ./build.sh -v -Ddisable_tests=1 --static
        '
      shell: pwsh
      env:
        NSS_DIR: /mnt/${{ github.workspace }}/nss
