name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install MozillaBuild
      run: |
        Invoke-WebRequest -Uri "https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe" -OutFile "MozillaBuildSetup.exe"
        Start-Process -FilePath .\MozillaBuildSetup.exe -Args '/S' -Wait -NoNewWindow
  
    - name: Setup Environment Variables
      run: |
        echo "MOZILLABUILD_PATH=C:\mozilla-build" >> $GITHUB_ENV
        echo "PATH=${env:MOZILLABUILD_PATH}\msys\bin;${env:MOZILLABUILD_PATH}\bin;${env:PATH}" >> $GITHUB_ENV

    - name: Install dependencies (Windows)
      uses: msys2/setup-msys2@v2
      with:
        install: nsinstall ninja python-six
        path-type: inherit

    - name: Install GYP
      run: |
        python3 -m pip install gyp-next
        echo "PATH=${env:PATH};${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\Enterprise\Common7\Tools" >> $GITHUB_ENV

    # - name: Clone and Extract NSS
    #   run: |
    #     Invoke-WebRequest -Uri "https://ftp.mozilla.org/pub/security/nss/releases/NSS_${{ env.VERSION_UNDERSCORED }}_RTM/src/nss-${{ env.VERSION }}.tar.gz" -OutFile "nss-${{ env.VERSION }}.tar.gz"
    #     tar -xzf "nss-${{ env.VERSION }}.tar.gz" -C "${{ env.NSS_DIR }}"
    #   env:
    #     VERSION: 3.45 # replace with actual version
    #     VERSION_UNDERSCORED: 3_45 # replace with actual version underscored
    #     NSS_DIR: ${{ github.workspace }}/nss
    
    - name: Clone and Extract NSS
      run: |
        $NSS_DIR = "D:\a\nss\nss"
        New-Item -ItemType directory -Path $NSS_DIR -Force
        Invoke-WebRequest -Uri "https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_80_RTM/src/nss-3.80.tar.gz" -OutFile "nss-3.80.tar.gz"
        tar -xzf "nss-3.80.tar.gz" -C $NSS_DIR
      shell: pwsh
    
    - name: Build NSS
      run: |
        $NSS_DIR = "D:\a\nss\nss"
        Set-Location -Path $NSS_DIR/nss-3.80
        Get-ChildItem -Path . # List contents to verify presence of build.sh
        bash ./build.sh -v -Ddisable_tests=1 --static
      shell: pwsh

    




