name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install MozillaBuild
      run: |
        Invoke-WebRequest -Uri "https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe" -OutFile "MozillaBuildSetup.exe"
        Start-Process -FilePath .\MozillaBuildSetup.exe -Args '/S' -Wait -NoNewWindow
    
    - name: Setup Environment Variables
      run: |
        echo "MOZILLABUILD_PATH=C:\mozilla-build" >> $GITHUB_ENV
        echo "PATH=${env:MOZILLABUILD_PATH}\msys\bin;${env:MOZILLABUILD_PATH}\bin;${env:PATH}" >> $GITHUB_ENV

    - name: Checkout NSS
      uses: actions/checkout@v2
      with:
        repository: 'nss-dev/nss'
        path: 'nss'

    - name: Setup NSS and NSPR
      run: |
        cd nss
        git submodule update --init
        cd ..
        hg clone https://hg.mozilla.org/projects/nspr

    - name: Build NSS
      run: |
        cd nss
        ./build.sh
      shell: bash
