name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install GYP
      run: pip install gyp-next

    - name: Install Visual Studio 2019 Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        choco install visualstudio2019-workload-vctools

    - name: Generate Visual Studio Project
      run: gyp nss.gyp --format=msvs -DOS=win

    - name: Build with Visual Studio 2019
      run: |
        "& 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe' nss.sln /p:Configuration=Release /p:Platform=x64"
