name: Build NSS on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        runtime: ["msvc", "mingw"]

    steps:
      - name: Install Visual Studio 2022 Build Tools
        uses: actions/setup-vcpkg@v3
        with:
          installer_url: https://github.com/Microsoft/vcpkg/releases/download/22.05/vcpkg-installer-2022.exe
          version: '22.05'

      - name: Checkout NSS source code
        uses: actions/checkout@v3

      - name: Install NSS dependencies
        run: |
          cd nss
          mkdir -p build
          cd build
          ${{ env.VCPKG_INSTALLATION }}/vcpkg install --triplet=x64-windows-static gyp ninja

      - name: Build NSS
        run: |
          cd nss
          mkdir -p dist
          cd build
          ./build.sh ${{ matrix.runtime }}

      - name: Install NSS build artifacts
        run: |
          cp -r dist/Debug ../build/nss-debug
          cp -r dist/Release ../build/nss-release

      - name: Upload NSS build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ../build
          name: NSS-build-artifacts
