name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install GYP
        run: pip install gyp-next

      - name: Install LLVM/Clang
        run: choco install llvm -y

      - name: Install Visual Studio 2019 Build Tools (Latest)
        uses: actions/setup-vcpkg@v2
        with:
          installer-url: https://github.com/Microsoft/vcpkg/releases/download/22.05/vcpkg-installer-2022.exe
          version: '22.05'

      - name: Prepare and Clone NSS and NSPR Repositories
        run: |
          if [ -d "nss" ]; then
            echo "Removing existing nss directory..."
            rm -rf nss
          fi

          if [ -d "nspr" ]; then
            echo "Removing existing nspr directory..."
            rm -rf nspr
          fi

          echo "Cloning NSS repository with --depth=1..."
          git clone --depth=1 https://github.com/nss-dev/nss.git

          echo "Cloning NSPR repository..."
          git clone https://hg.mozilla.org/projects/nspr
        shell: bash

      - name: Generate Visual Studio Project
        run: gyp nss/nss.gyp --format=msvs -DOS=win
        working-directory: ./nss

      - name: Build with Clang-CL
        run: |
          $env:CC = "clang-cl"
          $env:CXX = "clang-cl"
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe' nss.sln /p:Configuration=Release /p:Platform=x64
        shell: pwsh
        working-directory: ./nss
